FROM golang:1.15-alpine

RUN apk add --no-cache --update \
	git

# Set enviroment variables.
ENV WORKSPACE=github.com/qystishere/s7rss \
    GOPATH=/go \
	PATH="/go/bin:$PATH" \
	CGO_ENABLED=0

# Copy the local package files to the container's workspace. Add to GOPATH.
ADD . /go/src/${WORKSPACE}

# Set workdir.
WORKDIR /go/src/${WORKSPACE}

# Run tests.
CMD go test ./...
